-- 이름, 보호 시작일 조회 --
SELECT INS.NAME AS NAME, INS.DATETIME AS DATETIME
FROM ANIMAL_INS AS INS
-- 조인 시작 --
LEFT JOIN ANIMAL_OUTS AS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
-- 아직 입양을 못간(조건) --
WHERE OUTS.DATETIME IS NULL
-- 보호 시작일 순 정렬 --
ORDER BY DATETIME 
-- 3마리 리미트 --
LIMIT 3
