-- ID, NAME, 희귀도 출력 --
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE AS T
-- 부모 아이템 RARE 판단 --
JOIN ITEM_INFO AS P
ON T.PARENT_ITEM_ID = P.ITEM_ID
-- 자식 아이템 끌고 오기 --
JOIN ITEM_INFO AS C
ON T.ITEM_ID = C.ITEM_ID
-- RARE 선별 --
WHERE P.RARITY = 'RARE'
-- 아이템 ID 내림차 --
ORDER BY C.ITEM_ID DESC;