SELECT FI.ID AS ID, FNI.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH
FROM FISH_INFO AS FI
-- LEFT JOIN -> 이름 붙이는 역할 --
LEFT JOIN FISH_NAME_INFO AS FNI
    ON FI.FISH_TYPE = FNI.FISH_TYPE
-- WHERE 절로 () 튜플 값 비교 --
-- (TYPE, LENGTH) 값이 서브쿼리의  (TYPE, MAX(LENGTH)) 중에 있는지 검사 --
-- TYPE이 같고, LENGTH가 MAX인 물고기만 필터링 --
WHERE (FI.FISH_TYPE, FI.LENGTH) IN
        (SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE)
ORDER BY ID;