-- 제목, 게시글ID, 댓글 ID, 댓글 작성 ID, 댓글 내용, 댓글 작성일 조회 --
SELECT
    B.TITLE,
    R.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID, 
    R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
-- 2022년 10월에 작성 --
WHERE B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
-- 작성일 기준, 제목 기준 오름차순 -- 
ORDER BY R.CREATED_DATE, B.TITLE